import type {
  Company,
  BankingProduct,
  FinancialStatement,
  CompanyDocument,
  TimelineEvent,
  Notification,
} from './supabase';

export const MOCK_COMPANY_ID = '11111111-1111-1111-1111-111111111111';

export const mockCompany: Company = {
  id: MOCK_COMPANY_ID,
  name: 'Al-Masaref Industrial Co.',
  industry: 'Manufacturing',
  sector: 'Industrials',
  registration_number: 'CR-1010234567',
  tax_id: '300123456700003',
  founded_year: 1998,
  headquarters: 'Riyadh',
  country: 'Saudi Arabia',
  employees_count: 1240,
  annual_revenue: 850_000_000,
  website: 'https://almasaref.com.sa',
  description:
    'A leading Saudi Arabian industrial conglomerate specialising in steel fabrication, construction materials, and logistics solutions.',
  relationship_manager: 'Ahmed Al-Rashid',
  relationship_since: '2015-03-15',
  risk_rating: 'Medium',
  customer_segment: 'Corporate',
  status: 'Active',
  logo_initials: 'AM',
};

export const mockBankingProducts: BankingProduct[] = [
  {
    id: 'bp-001',
    company_id: MOCK_COMPANY_ID,
    product_type: 'Term Loan',
    product_name: 'Corporate Term Loan',
    account_number: 'SA22 1000 0001 2345 6789 0001',
    limit_amount: 50_000_000,
    outstanding_amount: 38_500_000,
    currency: 'SAR',
    start_date: '2021-06-01',
    expiry_date: '2026-05-31',
    status: 'Active',
  },
  {
    id: 'bp-002',
    company_id: MOCK_COMPANY_ID,
    product_type: 'Letter of Credit',
    product_name: 'Import LC Facility',
    account_number: 'SA22 1000 0001 2345 6789 0002',
    limit_amount: 20_000_000,
    outstanding_amount: 11_200_000,
    currency: 'SAR',
    start_date: '2023-01-15',
    expiry_date: '2025-01-14',
    status: 'Active',
  },
  {
    id: 'bp-003',
    company_id: MOCK_COMPANY_ID,
    product_type: 'Current Account',
    product_name: 'Main Operating Account',
    account_number: 'SA22 1000 0001 2345 6789 0003',
    limit_amount: null,
    outstanding_amount: 4_750_000,
    currency: 'SAR',
    start_date: '2015-03-15',
    expiry_date: null,
    status: 'Active',
  },
  {
    id: 'bp-004',
    company_id: MOCK_COMPANY_ID,
    product_type: 'Overdraft',
    product_name: 'Working Capital Overdraft',
    account_number: 'SA22 1000 0001 2345 6789 0004',
    limit_amount: 10_000_000,
    outstanding_amount: 6_300_000,
    currency: 'SAR',
    start_date: '2022-04-01',
    expiry_date: '2025-03-31',
    status: 'Active',
  },
  {
    id: 'bp-005',
    company_id: MOCK_COMPANY_ID,
    product_type: 'Bank Guarantee',
    product_name: 'Performance Bond — NEOM Project',
    account_number: 'BG-20240078',
    limit_amount: 5_000_000,
    outstanding_amount: 5_000_000,
    currency: 'SAR',
    start_date: '2024-02-10',
    expiry_date: '2025-02-09',
    status: 'Expired',
  },
];

export const mockFinancialStatements: FinancialStatement[] = [
  {
    id: 'fs-2024',
    company_id: MOCK_COMPANY_ID,
    year: 2024,
    total_assets: 1_240_000_000,
    total_liabilities: 740_000_000,
    total_equity: 500_000_000,
    total_revenue: 850_000_000,
    gross_profit: 212_500_000,
    operating_income: 127_500_000,
    net_income: 93_500_000,
    operating_cash_flow: 118_000_000,
    investing_cash_flow: -42_000_000,
    financing_cash_flow: -35_000_000,
    current_ratio: 1.82,
    debt_to_equity: 1.48,
    return_on_equity: 18.7,
    return_on_assets: 7.5,
    gross_margin: 25.0,
    net_margin: 11.0,
  },
  {
    id: 'fs-2023',
    company_id: MOCK_COMPANY_ID,
    year: 2023,
    total_assets: 1_150_000_000,
    total_liabilities: 710_000_000,
    total_equity: 440_000_000,
    total_revenue: 790_000_000,
    gross_profit: 190_000_000,
    operating_income: 110_000_000,
    net_income: 79_000_000,
    operating_cash_flow: 98_000_000,
    investing_cash_flow: -38_000_000,
    financing_cash_flow: -28_000_000,
    current_ratio: 1.71,
    debt_to_equity: 1.61,
    return_on_equity: 17.9,
    return_on_assets: 6.9,
    gross_margin: 24.1,
    net_margin: 10.0,
  },
  {
    id: 'fs-2022',
    company_id: MOCK_COMPANY_ID,
    year: 2022,
    total_assets: 1_050_000_000,
    total_liabilities: 650_000_000,
    total_equity: 400_000_000,
    total_revenue: 710_000_000,
    gross_profit: 163_000_000,
    operating_income: 95_000_000,
    net_income: 66_000_000,
    operating_cash_flow: 81_000_000,
    investing_cash_flow: -30_000_000,
    financing_cash_flow: -22_000_000,
    current_ratio: 1.65,
    debt_to_equity: 1.63,
    return_on_equity: 16.5,
    return_on_assets: 6.3,
    gross_margin: 23.0,
    net_margin: 9.3,
  },
];

export const mockDocuments: CompanyDocument[] = [
  {
    id: 'doc-001',
    company_id: MOCK_COMPANY_ID,
    document_type: 'Commercial Registration',
    document_name: 'Commercial Registration Certificate',
    status: 'Needs Update',
    expiry_date: '2025-09-30',
    upload_date: '2022-10-01',
    issuing_authority: 'Ministry of Commerce',
    notes: 'Renewal due within 90 days',
    required_for: ['KYC', 'Corporate Onboarding'],
  },
  {
    id: 'doc-002',
    company_id: MOCK_COMPANY_ID,
    document_type: 'Articles of Association',
    document_name: 'Articles of Association & Bylaws',
    status: 'Complete',
    expiry_date: null,
    upload_date: '2023-02-14',
    issuing_authority: 'Ministry of Justice',
    notes: null,
    required_for: ['Corporate Onboarding'],
  },
  {
    id: 'doc-003',
    company_id: MOCK_COMPANY_ID,
    document_type: 'Financial Statements',
    document_name: 'Audited Financial Statements 2024',
    status: 'Complete',
    expiry_date: null,
    upload_date: '2025-03-20',
    issuing_authority: 'KPMG Al-Fozan & Partners',
    notes: null,
    required_for: ['Credit Facility', 'KYC'],
  },
  {
    id: 'doc-004',
    company_id: MOCK_COMPANY_ID,
    document_type: 'Authorised Signatories',
    document_name: 'Authorised Signatories List',
    status: 'Missing',
    expiry_date: null,
    upload_date: null,
    issuing_authority: null,
    notes: 'Required for all new facilities',
    required_for: ['Credit Facility', 'Corporate Onboarding'],
  },
  {
    id: 'doc-005',
    company_id: MOCK_COMPANY_ID,
    document_type: 'VAT Certificate',
    document_name: 'VAT Registration Certificate',
    status: 'Complete',
    expiry_date: null,
    upload_date: '2023-05-11',
    issuing_authority: 'ZATCA',
    notes: null,
    required_for: ['KYC'],
  },
  {
    id: 'doc-006',
    company_id: MOCK_COMPANY_ID,
    document_type: 'Board Resolution',
    document_name: 'Board Resolution for Banking',
    status: 'Missing',
    expiry_date: null,
    upload_date: null,
    issuing_authority: null,
    notes: 'Required for credit renewal',
    required_for: ['Credit Facility'],
  },
];

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: 'te-001',
    company_id: MOCK_COMPANY_ID,
    event_type: 'Review',
    title: 'Annual Credit Review Completed',
    description: 'Annual credit review completed. Term loan limit maintained at SAR 50M. Risk rating remains Medium.',
    event_date: '2024-11-15',
    created_by: 'Ahmed Al-Rashid',
  },
  {
    id: 'te-002',
    company_id: MOCK_COMPANY_ID,
    event_type: 'Document',
    title: 'Audited Financials Received',
    description: 'FY2024 audited financial statements received and uploaded to the system.',
    event_date: '2025-03-20',
    created_by: 'Fatima Al-Zahrani',
  },
  {
    id: 'te-003',
    company_id: MOCK_COMPANY_ID,
    event_type: 'Alert',
    title: 'Commercial Registration Expiry Alert',
    description: 'System alert triggered: Commercial Registration expires in 90 days. Customer notified via email.',
    event_date: '2025-07-01',
    created_by: 'System',
  },
  {
    id: 'te-004',
    company_id: MOCK_COMPANY_ID,
    event_type: 'Meeting',
    title: 'RM Client Meeting',
    description: 'Quarterly relationship meeting held at client headquarters. Discussed expansion plans and additional financing needs.',
    event_date: '2025-04-10',
    created_by: 'Ahmed Al-Rashid',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    company_id: MOCK_COMPANY_ID,
    title: 'Commercial Registration Expiring',
    message: 'Al-Masaref Industrial Co. Commercial Registration expires in 77 days. Action required.',
    type: 'warning',
    priority: 'High',
    is_read: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'notif-002',
    company_id: MOCK_COMPANY_ID,
    title: 'Missing Documents Detected',
    message: '2 required documents are missing: Authorised Signatories List, Board Resolution for Banking.',
    type: 'error',
    priority: 'Critical',
    is_read: false,
    created_at: new Date().toISOString(),
  },
];
