export const policyEngine = {
  bankingPolicies: [
    { id: 'BP-001', category: 'Credit Risk', title: 'Credit Facility Approval Policy', description: 'All credit facilities above SAR 50M require Credit Committee approval. Facilities above SAR 500M require Board approval.', lastUpdated: '2024-01-01' },
    { id: 'BP-002', category: 'KYC & AML', title: 'Annual KYC Refresh Policy', description: 'Corporate customers must undergo KYC refresh annually. Any KYC not refreshed within 12 months must be flagged as overdue.', lastUpdated: '2024-01-01' },
    { id: 'BP-003', category: 'Document Management', title: 'Document Validity Policy', description: 'All customer documents must be valid and unexpired. Documents expiring within 90 days must be flagged for renewal.', lastUpdated: '2024-01-01' },
    { id: 'BP-004', category: 'AML/CFT', title: 'UBO Disclosure Policy', description: 'All corporate customers must submit a UBO Declaration disclosing all beneficial owners holding 25% or more ownership.', lastUpdated: '2024-01-01' },
    { id: 'BP-005', category: 'Credit Risk', title: 'Financial Statement Requirements', description: 'Latest audited financial statements (not older than 18 months) are required for all credit facilities and renewals.', lastUpdated: '2024-01-01' },
    { id: 'BP-006', category: 'Risk Management', title: 'Risk Rating Review Policy', description: 'Customer risk ratings must be reviewed annually. Material changes in financial condition require immediate reassessment.', lastUpdated: '2024-01-01' },
  ],
  operationalProcedures: [
    {
      id: 'OP-001',
      title: 'Corporate Account Opening Procedure',
      steps: [
        'Collect and verify all mandatory documents',
        'Complete corporate KYC form',
        'Obtain UBO Declaration',
        'Perform AML/sanctions screening',
        'Risk rating assignment',
        'Relationship Manager approval',
        'Operations team account activation',
      ],
    },
    {
      id: 'OP-002',
      title: 'Credit Facility Renewal Procedure',
      steps: [
        'Request updated financial statements',
        'Review commercial registration validity',
        'Update KYC if overdue',
        'Conduct financial analysis',
        'Prepare credit memo',
        'Submit for appropriate approval level',
        'Issue facility letter upon approval',
      ],
    },
    {
      id: 'OP-003',
      title: 'Document Collection Procedure',
      steps: [
        'Identify missing or expired documents',
        'Issue document request to customer',
        'Verify document authenticity',
        'Upload to document management system',
        'Update compliance checklist',
        'Notify compliance team of completion',
      ],
    },
  ],
  kycRequirements: {
    mandatoryInformation: [
      'Legal company name',
      'Commercial registration number',
      'Tax identification number',
      'Registered address',
      'Business activity description',
      'Authorized signatories and their IDs',
      'UBO information (ownership 25%+)',
      'Financial statements (latest 2 years)',
      'Source of funds declaration',
    ],
    mandatoryDocuments: [
      'Commercial Registration Certificate',
      'Articles of Association',
      'Board Resolution (for account opening)',
      'Authorized Signatory National IDs',
      'UBO Declaration Form',
      'ZATCA Tax Registration Certificate',
    ],
  },
  requiredDocumentsLibrary: {
    'Corporate Account Opening': [
      'Commercial Registration Certificate',
      'Articles of Association',
      'Board Resolution',
      'Authorized Signatory National IDs',
      'UBO Declaration',
      'ZATCA Tax Registration Certificate',
      'Corporate KYC Form',
    ],
    'Credit Facility / Working Capital Finance': [
      'Commercial Registration Certificate',
      'Audited Financial Statements (latest 2 years)',
      'Cash Flow Projections',
      'Management Accounts',
      'Facility Purpose Documentation',
      'UBO Declaration',
    ],
    'Trade Finance (LC / LG)': [
      'Commercial Registration Certificate',
      'Trade Contract / Purchase Order',
      'Financial Statements',
      'Facility Application Form',
    ],
    'Project Finance': [
      'Commercial Registration Certificate',
      'Project Feasibility Study',
      'Audited Financial Statements (latest 3 years)',
      'Project Contracts',
      'Environmental Impact Assessment (if applicable)',
      'Government Approvals/Permits',
    ],
  },
  businessRules: [
    { id: 'BR-001', condition: 'Commercial Registration is expired or expiring within 90 days', action: 'Request renewal before continuing any credit facility processing or account changes.', priority: 'High' },
    { id: 'BR-002', condition: 'Financial Statements are older than 18 months', action: 'Request latest audited financial statements before processing credit requests.', priority: 'High' },
    { id: 'BR-003', condition: 'KYC form not refreshed within 12 months', action: 'Initiate annual KYC refresh process immediately.', priority: 'Medium' },
    { id: 'BR-004', condition: 'UBO Declaration is missing', action: 'Request UBO Declaration as per AML/CFT policy before proceeding with any banking relationship.', priority: 'High' },
    { id: 'BR-005', condition: 'Authorized Signatory ID is expired', action: 'Request updated National ID and re-verify signatory authority before processing transactions.', priority: 'High' },
    { id: 'BR-006', condition: 'Credit facility approaching expiry (within 60 days)', action: 'Initiate renewal process: collect documents, update financials, prepare credit memo.', priority: 'Medium' },
    { id: 'BR-007', condition: 'Risk rating deterioration detected', action: 'Escalate to Risk Management for immediate review and potential credit action.', priority: 'High' },
    { id: 'BR-008', condition: 'All documents complete and KYC current', action: 'Proceed to next processing stage as per operational procedure.', priority: 'Low' },
  ],
};
